### ISSUE TITLE
Unregister not registered User model

### ISSUE THREAD

**Issue by mbourqui** [jhuapl-boss/boss-oidc#16]
In the `admin.py`, it tries to re-register the `User` model. But this latter is not registered when using a custom User model, thus generating an exception while unregistering.
Or the `User` may not be registered at all for any other reason, thus also generating the exception.

**Comment by derek-pryor** [comment]
You are correct.

Since this library is targeted for our use we have registered the regular User model. If you want to submit a PR we will accept it. Since our use case works this will be a low priority for us to fix.

**Comment by mbourqui** [comment]
I was about to submit a PR anyway ;)
ETA before Monday.
