### ISSUE TITLE
Finding the Keycloak Authentication HTTP Header token

### ISSUE THREAD

**Issue by jonalv** [jhuapl-boss/boss-oidc#2]
I am building a service that is to integrate and use other services. In order to us the other services I need to authenticate with them using the Keycloak token. It seems the Django approach would be to look for the Keycloak token in the `META` dictionary of the `request` but it doesn't seem to be there. Is boss-oidc swallowing it whole? Is that by design? Is there another way to get hold of it?

**Comment by derek-pryor** [comment]
Boss-oidc is more a wrapper around django-oidc and drf-oidc-auth, allowing
you to configure both together. The specifics of how each authentication
mechanism works is still left to each of those plugins.

If the user to your service is authenticating using a Keycloak (bearer)
token, then the token will be in the Authorization (I believe) header of
the request. This would be handled by the drf-oidc-auth plugin. If the user
is authenticating to your service using redirects (not sure the exact name
for this mode) and the django-oidc plugin then you may need to make a call
to the Keycloak server to request the token for the user. (It may be
possible to grab it during the login process) I'm not sure the specifics as
we've never tried to pass on the user's token after they log into our
service.

-Derek
