### ISSUE TITLE
Working with Reverse Proxy

### ISSUE THREAD

**Issue by ST2Labs** [jhuapl-boss/boss-oidc#25]
Hi,

I'm trying to deploy keycloak + django in docker container, but when I use internal "uri" doesn't work,

It's possible to use intenal uri to internal comunications, and handle public uri to login and redirect ?

I'll try but I have error keyjar !

Thanks in advanced

**Comment by derek-pryor** [comment]
My understanding of OpenID Connect is that normally all URIs are discovered from the authentication service. Because of this a common base URI is normally used for all of the different URIs. It may be possible but this is outside the scope of our deployments.
