### ISSUE TITLE
setup.py does not install migrations

### ISSUE THREAD

**Issue by ricardogsilva** [jhuapl-boss/boss-oidc#28]
When using pip to install this project as in 

```
pip install git+https://github.com/jhuapl-boss/boss-oidc.git@v1.2.0
```

The `migrations` directory is not included in the final installation. This is due to a bug in `setup.py`, where the `setup()` function is receiving:

```python
setup(
   ...
    packages=["bossoidc",]
   ...
)
```

The fix is just a matter of adding the migrations directory to packages, like:

```python
setup(
   ...
    packages=[
        "bossoidc", 
        "bossoidc/migrations"
    ]
   ...
)
```

Alternatively, `setup.py` could make `setuptools` a mandatory dependency and just use:

```python
setup(
   ...
    packages=find_packages()
   ...
)
```

**Comment by derek-pryor** [comment]
Bumped version number to `v1.2.1`
