### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Giovanni-94** [jhuapl-boss/boss-oidc#7]
Hi we are trying to integrate your library,

is there any way to authenticate user on Keycloak with OpenIdConnectBackend.authenticate?

Thanks in advance

Regards.

**Comment by derek-pryor** [comment]
If you install and configure boss-oidc, django-oidc, and drf-oidc-auth then when the user tries to access a login required page they will be redirected to Keycloak to authenticate. Once Keycloak verifies the user's password it redirects the user back to Django.

There are other Open ID Connect workflows that allow other types of logins, such as the application getting the user's username and password and then the application logging into Keycloak on behalf of the user. That workflow is outside the scope of this plugin. A bearer token retrieved this way can be used to authenticate with boss-oidc (using drf-oidc-auth) by passing it as a HTTP header with the request.

**Comment by Allan-Nava** [comment]
Hi @derek-pryor ,
How can I redirect to the keycloak page login?? 
I need a custom decorator for **login_required**

Thanks in advance

**Comment by derek-pryor** [comment]
When you run `from bossoidc.settings import *` in your `settings.py` it configures the `LOGIN_URL` and `LOGOUT_URL` Django settings. From there you just use the regular `@login_required` or `LoginRequiredMixin` constructs. If you are using a custom decorator the make sure it used `settings.LOGIN_URL` as the location to log the user in.

**Comment by Allan-Nava** [comment]
@derek-pryor Can you give me an example, please?

Thanks

**Comment by derek-pryor** [comment]
@Allan-Nava You should be able to use any existing Django examples on how to create a custom `@login_required` decorator. Boss-oidc conforms to the Django login system and all you need to do is issue a redirect to the url defined in `settings.LOGIN_URL`

**Comment by Allan-Nava** [comment]
Hi @derek-pryor ,

I got this error:
**Received state not the same as expected**

```
Request Method: | GET
-- | --
http://192.168.1.50:8080/openid/callback/login/?state=Kx4kDQeKx9eIf2yi&code=nJkevjwcvG6TtuXKkH01VttXeduv2CKiO9FcYMFy3w4.041cb6c1-82a6-47cd-b09c-08fcc7a61dbe
1.11.5
TypeError
authenticate() argument after ** must be a mapping, not OIDCError
/usr/local/lib/python3.5/dist-packages/djangooidc/views.py in authz_cb, line 89
/usr/bin/python3

Request Method: | GET
-- | --
http://192.168.1.50:8080/openid/callback/login/?state=Kx4kDQeKx9eIf2yi&code=nJkevjwcvG6TtuXKkH01VttXeduv2CKiO9FcYMFy3w4.041cb6c1-82a6-47cd-b09c-08fcc7a61dbe
1.11.5
TypeError
authenticate() argument after ** must be a mapping, not OIDCError
/usr/local/lib/python3.5/dist-packages/djangooidc/views.py in authz_cb, line 89
/usr/bin/python3

```


How can I fix this error?

**Comment by derek-pryor** [comment]
@Allan-Nava This is a bug in the django-oidc plugin. Please open an issue with that repository.

Since the original issue did not contain a bug with the boss-oidc plugin I am closing the issue.

**Comment by Allan-Nava** [comment]
Ok, @derek-pryor
